Repository Donggrami/Earth1round-iOS, pull requests merged in 2022-07, with the labels that each got.

#2 [chore] project init
  .gitignore
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.pbxproj
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Earth1round-iOS/Earth1round-iOS/.swiftlint.yml
  Earth1round-iOS/Earth1round-iOS/Info.plist
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/Contents.json
  Earth1round-iOS/Earth1round-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  Earth1round-iOS/Earth1round-iOS/Resource/Support/AppDelegate.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Support/Base.lproj/LaunchScreen.storyboard
  Earth1round-iOS/Earth1round-iOS/Resource/Support/SceneDelegate.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/ViewController.swift
Labels: 🫧 novv, 🎈 chore

#5 [feat] 캘린더, 캐릭터 꾸미기, 코스 선택 와이어프레임
  Earth1round-iOS/.swiftlint.yml
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.pbxproj
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/backButton.imageset/Contents.json
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/backButton.imageset/backButton.png
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/backButton.imageset/backButton@2x.png
  Earth1round-iOS/Earth1round-iOS/Resource/Assets.xcassets/backButton.imageset/backButton@3x.png
  Earth1round-iOS/Earth1round-iOS/Resource/Constants/Size.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Extensions/NSObject+ClassName.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Extensions/UICollectionView+Generic.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Extensions/UINavigationController+Extensions.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Extensions/UINavigationItem+Extensions.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Extensions/UIVIew+addSubViews.swift
  Earth1round-iOS/Earth1round-iOS/Resource/Support/Info.plist
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/Base/BaseViewController.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/Cells/CharacterCollectionViewCell.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/CalendarViewController.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/CharacterSelectionViewController.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/CourseViewController.swift
Labels: 👀 style, 🫧 novv

#7 #3 home view pull request
  Earth1round-iOS/Earth1round-iOS.xcodeproj/project.pbxproj
  Earth1round-iOS/Earth1round-iOS.xcodeproj/xcshareddata/xcschemes/Earth1round-iOS.xcscheme
  Earth1round-iOS/Earth1round-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  Earth1round-iOS/Earth1round-iOS/Resource/Support/SceneDelegate.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/EarthViewController.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/HomeViewController.swift
  Earth1round-iOS/Earth1round-iOS/Source/Presentation/ViewControllers/ViewController.swift
Labels: 👀 style, ✨ kyo
